### ISSUE TITLE
Incorrect state

### ISSUE THREAD

**Issue by sickboards** [bitpay/prestashop-v2#8]
Hello (again)
We are running the module on ps 1.7.5.2
The Front works okay, only in the BO there is an issue
The orders are not getting the correct state. 
In both cases unsuccessful and successful they go from state id=10 (awaiting bank wire payment) to id=3 (unknown/not a valid state in my shop).
So there does not seem to be a correct postback (in either case) and not a correct configuration of states

**Comment by thejoshualewis** [comment]
Hello,

You should be able to map orders (screenshot attached) for Confirmed/Expired orders, as well as add an Error status.  You might have to create one by going to Configure->Shop Parameters->Order Settings->Statuses, and create a custom one there.

<img width="1067" alt="screenshot" src="https://user-images.githubusercontent.com/392836/98253624-44117300-1f49-11eb-9368-cec604edce33.png">

<img width="1162" alt="screenshot_1" src="https://user-images.githubusercontent.com/392836/98253819-82a72d80-1f49-11eb-9a3d-a8240a2009bb.png">

**Comment by sickboards** [comment]
Hi

I have them mapped, but it does not seem to use that order state,
I have remapped them and created an extra error state for bit pay
what I also noticed it that it shows the states for every language which is
weird:
[image: image.png]
Let's see if it makes a difference
Where are the state mappings stored? in the ps_configuration table?

**Comment by sickboards** [comment]
Found it,
it seems it does not create a correct key
for bitpay_checkout_ipn_map_confirmed
[image: image.png]
It is missing the one for shop 1
I will manually add it to see if it helps

**Comment by sickboards** [comment]
Unfortunately it is still not working, am I missing any configuration settings? Please know that I have a multi store configuration
![image](https://user-images.githubusercontent.com/3520123/98802817-24c88900-2414-11eb-84cb-a94fb7576aea.png)

**Comment by sickboards** [comment]
Hi 
I think I have found a possible cause of the problem. The module uses hard-coded states nrs(!) in ipn.php
Please don't do that, get them from the database, not everyone is using the same state sequence!
`case 'invoice_paidInFull': #pending
                    #update the order and history
                    if ($orderStatus->data->status == 'paid'):
                        $current_state = 3;
                        $current_state = (int)$current_state;
                        $db = Db::getInstance();
                        $bp_u = "UPDATE $order_table SET current_state = $current_state WHERE id_order = '$orderId'";
                        $db->Execute($bp_u);

                        #update the transaction table
                        $bp_t = "UPDATE $table_name SET transaction_status = '$transaction_status' WHERE transaction_id = '$transaction_id' AND order_id = $orderId";
                        $db->Execute($bp_t);

                        #update the history table
                        $bp_h = "INSERT INTO $order_history_table (id_employee,id_order,id_order_state,date_add)
									        VALUES (0,'$orderId',$current_state,NOW())";
                        $db->Execute($bp_h);
                    endif;`

**Comment by sickboards** [comment]
And there is a timing issue as well is id_order_history = 605722 is newer than 605723 (i don't know if that has an impact)
![image](https://user-images.githubusercontent.com/3520123/99044055-76e1e980-258f-11eb-8a11-df45d72e01d7.png)

**Comment by thejoshualewis** [comment]
Hi there,

We updated the plugin, and added more IPN updates that are now configurable.
https://github.com/bitpay/prestashop-v2/releases/tag/v11.13.2020

**Comment by sickboards** [comment]
Hi thank you
I have installed the new module but the problems are still there

- the incorrect timing of the order states
- and there does not seem to be a postback if an order is successful or
failed

**Comment by PascalCoinDev** [comment]
I have the same issue, on Prestashop 1.7.6.5  (I think issue is the same on newer/older Prestashop versions)

Please, as said by sickboards
- the incorrect timing of the order states
- and there does not seem to be a postback if an order is successful or failed
